String function for Status
connectrpc/grpchealth-go pull request #58
Opened 2023-09-06 01:32 UTC by VoyTechnology

Viewing the status code as a string is a bit awkward if we use int. The change adds the String function so that it's more human readable.

2023-09-06 01:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/connectrpc/grpchealth-go?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/connectrpc/grpchealth-go?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/connectrpc/grpchealth-go?pullRequest=58) it.</sub>

2023-09-06 03:55 UTC, akshayjshah requested changes
Thanks for the PR, @VoyTechnology! This is generally a good idea.

Before we merge this, can you change the code to follow the casing convention we're using for `connect.Code`? The code is [here](https://github.com/connectrpc/connect-go/blob/main/code.go#L110). Please also handle unknown values the way they are in `connect.Code`, and add a simple unit test.

2023-09-19 20:42 UTC, VoyTechnology commented
Hi @akshayjshah, I have updated the PR with your requested changes. Since there are fewer statuses than codes, I manually create a list of valid status codes to check against.

2023-10-03 19:30 UTC, akshayjshah approved these changes
Looks good to me! I added a bit of logic to the tests to use `testing/quick` to test more status constants, but the rest of the change is nice. Thank you for the contribution, @VoyTechnology!

2023-10-03 19:30 UTC, merged